apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: devel
    app.openshift.io/vcs-uri: 'https://github.com/NicolasO/front-end'
    app.openshift.io/connects-to: 'catalogue,payment,orders,carts,user,shipping'
  name: front-end
  namespace: socks-shop-dev
spec:
  selector:
    app: front-end
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: quay.io/nicolaso/front-end:devel
          ports:
            - containerPort: 8079
