apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: socks-shop
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8079
  selector:
    app: front-end
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
