apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-api-repo-webhook-run
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "nicolaso"
    - name: GitHubUser
      value: "nicolaso"
    - name: GitHubRepo
      value: "front-end"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: <route url from previous section>
  timeout: 1000s
  serviceAccount: tekton-triggers-createwebhook
