apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-pipelinerun-
spec:
  pipelineRef:
    name: build-and-deploy
  resources:
    - name: front-end-repo
      resourceRef:
        name: front-end-repo
    - name: front-end-image
      resourceRef:
        name: front-end-image
