apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  resources:
    - name: front-end-repo
      type: git
    - name: front-end-image
      type: image

  tasks:
    - name: build-front-end
      taskRef:
        name: buildah
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: front-end-repo
        outputs:
          - name: image
            resource: front-end-image
      params:
        - name: TLSVERIFY
          value: "false"

    - name: apply-front-end-manifests
      taskRef:
        name: apply-manifests
      resources:
        inputs:
          - name: source
            resource: front-end-repo
      runAfter:
        - build-front-end

    - name: update-front-end-image
      taskRef:
        name: update-deployment
      resources:
        inputs:
          - name: image
            resource: front-end-image
      params:
        - name: deployment
          value: "front-end"
      runAfter:
        - apply-front-end-manifests
