apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  serviceAccountName: build-registry
  resources:
    - name: front-end-repo
      type: git
    - name: front-end-image
      type: image

  tasks:
    - name: build-front-end
      taskRef:
        name: buildah
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: front-end-repo
        outputs:
          - name: image
            resource: front-end-image
      params:
        - name: TLSVERIFY
          value: "false"

    - name: deploy-web
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-skaffold-web
      params:
        - name: path
          value: /workspace/source/deployment/front-end.yaml
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
