apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
secrets:
  - name: regcred

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-registry
secrets:
  - name: regcred

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: front-end-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/NicolasO/front-end.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: front-end-image
spec:
  type: image
  params:
    - name: url
      value: quay.io/nicolaso/front-end:latest

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: unit-test
spec:
  steps:
    - command:
        - /bin/bash
        - '-c'
        - echo
        - Unit test OK
      image: registry.redhat.io/ubi7/ubi-minimal
      name: ''
      resources: {}
---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: functional-test
spec:
  steps:
    - command:
        - /bin/bash
        - '-c'
        - echo
        - functional test ok
      image: registry.redhat.io/ubi7/ubi-minimal
      name: ''
      resources: {}

---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-to-dev
spec:
  resources:
    - name: front-end-repo
      type: git
    - name: front-end-image
      type: image

  tasks:
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: front-end-repo
        outputs:
          - name: image
            resource: front-end-image
      params:
        - name: TLSVERIFY
          value: "false"

    - name: unit-test
      runAfter:
        - build
      taskRef:
        kind: Task
        name: unit-test

    - name: deploy-to-dev
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - unit-test
      params:
        - name: ARGS
          value:
            - rollout
            - latest
            - front-end
    - name: functional-test
      runAfter:
        - deploy-to-dev
      taskRef:
        kind: Task
        name: functional-test
#---
#apiVersion: tekton.dev/v1alpha1
#kind: PipelineRun
#metadata:
#  generateName: build-and-deploy-pipelinerun-
#spec:
#  serviceAccountName: build-registry
#  pipelineRef:
#    name: build-and-deploy
#  resources:
#    - name: front-end-repo
#      resourceRef:
#        name: front-end-repo
#    - name: front-end-image
#      resourceRef:
#        name: front-end-image
