apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-registry
secrets:
  - name: regcred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
secrets:
  - name: regcred
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: front-end-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/NicolasO/front-end.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: front-end-image
spec:
  type: image
  params:
    - name: url
      value: quay.io/nicolaso/front-end:latest
---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy
spec:
  resources:
    - name: front-end-repo
      type: git
    - name: front-end-image
      type: image

    - name: deploy-front-end
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: ARGS
          value:
            - rollout
            - latest
            - front-end

#---
#apiVersion: tekton.dev/v1alpha1
#kind: PipelineRun
#metadata:
#  generateName: build-and-deploy-pipelinerun-
#spec:
#  serviceAccountName: build-registry
#  pipelineRef:
#    name: build-and-deploy
#  resources:
#    - name: front-end-repo
#      resourceRef:
#        name: front-end-repo
#    - name: front-end-image
#      resourceRef:
#        name: front-end-image
